import { readIndex } from '../store/mod.js';
import { AnyNode, NodeType } from '../schema/mod.js';
import { loadNodes } from '../commands/utils.js';
import path from 'path';

export interface ExportOptions {
  type?:     string;
  scope?:    string;
  verified?: boolean;
  noHeader?: boolean;
}

export interface ExportResult {
  nodes:     AnyNode[];
  markdown:  string;
  nodeCount: number;
}

export function exportNodes(root: string, options: ExportOptions = {}): ExportResult {
  const nodes = loadNodes(root, { type: options.type, scope: options.scope, verified: options.verified });

  if (nodes.length === 0) {
    return { nodes: [], markdown: '', nodeCount: 0 };
  }

  const index    = readIndex(root);
  const repo     = index?.repo ?? path.basename(root);
  const markdown = buildMarkdown(nodes, repo, options.noHeader);

  return { nodes, markdown, nodeCount: nodes.length };
}

function buildMarkdown(nodes: AnyNode[], repo: string, noHeader?: boolean): string {
  const lines: string[] = [];

  if (!noHeader) {
    lines.push(`# Filer Knowledge Layer — ${repo}`);
    lines.push('');
    lines.push(`> Generated by [Filer](https://github.com/dkeswani/filer) · ${new Date().toISOString().slice(0, 10)} · ${nodes.length} node(s)`);
    lines.push('');
    lines.push('This file contains structured knowledge extracted from the codebase. Load it before writing code to understand constraints, dangers, patterns, and decisions that are not visible from reading the code alone.');
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  const byType = new Map<NodeType, AnyNode[]>();
  for (const node of nodes) {
    const list = byType.get(node.type) ?? [];
    list.push(node);
    byType.set(node.type, list);
  }

  const TYPE_HEADINGS: Record<string, string> = {
    security:    '## Security Rules',
    constraint:  '## Constraints',
    danger:      '## Dangers',
    assumption:  '## Assumptions',
    antipattern: '## Antipatterns',
    pattern:     '## Patterns',
    intent:      '## Module Intent',
    decision:    '## Decisions',
  };

  for (const [type, typeNodes] of byType) {
    lines.push(TYPE_HEADINGS[type] ?? `## ${type}`);
    lines.push('');
    for (const node of typeNodes) {
      lines.push(`### \`${node.id}\``);
      lines.push('');
      lines.push(`**Scope:** ${node.scope.join(', ')}`);
      lines.push(`**Confidence:** ${Math.round(node.confidence * 100)}%`);
      if (node.verified) lines.push('**Verified:** ✓');
      lines.push('');

      switch (node.type) {
        case 'security':
          lines.push(`**Severity:** ${node.severity.toUpperCase()}`);
          lines.push(`**Category:** ${node.category}`);
          lines.push(`**Rule:** ${node.statement}`);
          lines.push(`**Because:** ${node.because}`);
          lines.push(`**If violated:** ${node.if_violated}`);
          lines.push(`**Safe pattern:** ${node.safe_pattern}`);
          break;
        case 'constraint':
          lines.push(`**Statement:** ${node.statement}`);
          lines.push(`**Because:** ${node.because}`);
          lines.push(`**If violated:** ${node.if_violated}`);
          if (node.instead) lines.push(`**Instead:** ${node.instead}`);
          break;
        case 'danger':
          lines.push(`**Statement:** ${node.statement}`);
          lines.push(`**Condition:** ${node.condition}`);
          lines.push(`**Safe pattern:** ${node.safe_pattern}`);
          break;
        case 'assumption':
          lines.push(`**Statement:** ${node.statement}`);
          lines.push(`**Breaks when:** ${node.breaks_when}`);
          if (node.boundary) lines.push(`**Boundary:** ${node.boundary}`);
          break;
        case 'antipattern':
          lines.push(`**Statement:** ${node.statement}`);
          lines.push(`**Correct pattern:** ${node.correct_pattern}`);
          break;
        case 'pattern':
          lines.push(`**Statement:** ${node.statement}`);
          lines.push(`**Why:** ${node.why}`);
          break;
        case 'intent':
          lines.push(`**Purpose:** ${node.purpose}`);
          break;
        case 'decision':
          lines.push(`**Statement:** ${node.statement}`);
          lines.push(`**Reason:** ${node.reason}`);
          break;
      }
      lines.push('');
      lines.push('---');
      lines.push('');
    }
  }

  return lines.join('\n');
}
