import type { PackedFile } from './scanner.js';

export type OutputFormat = 'markdown' | 'xml' | 'json' | 'plain';

export interface FormatOptions {
  format:          OutputFormat;
  files:           PackedFile[];
  tree?:           string;
  preamble?:       string;    // knowledge summary
  instructions?:   string;    // from filer.md or --instructions
  headerText?:     string;
  showLineNumbers?: boolean;
  repoName:        string;
  generatedAt:     string;
  totalTokens:     number;
  totalFiles:      number;
  topFilesLen?:    number;
}

export function formatOutput(opts: FormatOptions): string {
  switch (opts.format) {
    case 'xml':      return formatXml(opts);
    case 'json':     return formatJson(opts);
    case 'plain':    return formatPlain(opts);
    case 'markdown':
    default:         return formatMarkdown(opts);
  }
}

// ── Markdown ──────────────────────────────────────────────────────────────────

function formatMarkdown(opts: FormatOptions): string {
  const parts: string[] = [];

  parts.push(`# ${opts.repoName} — Filer Pack`);
  parts.push('');
  parts.push(`> Generated by [Filer](https://github.com/dkeswani/filer) · ${opts.generatedAt} · ${opts.totalFiles} files · ~${opts.totalTokens.toLocaleString()} tokens`);
  parts.push('');

  if (opts.headerText) {
    parts.push(opts.headerText, '');
  }

  if (opts.instructions) {
    parts.push('## Instructions', '', opts.instructions, '', '---', '');
  }

  if (opts.preamble) {
    parts.push(opts.preamble);
  }

  if (opts.tree) {
    parts.push('## Repository Structure', '', '```', opts.tree, '```', '');
  }

  if (opts.topFilesLen && opts.topFilesLen > 0) {
    parts.push('## Largest Files', '');
    const top = [...opts.files]
      .sort((a, b) => b.tokens - a.tokens)
      .slice(0, opts.topFilesLen);
    for (const f of top) {
      parts.push(`- \`${f.path}\` — ~${f.tokens.toLocaleString()} tokens`);
    }
    parts.push('');
  }

  parts.push('## Files', '');

  for (const file of opts.files) {
    parts.push(`### \`${file.path}\``);
    parts.push('');
    const content = opts.showLineNumbers ? addLineNumbers(file.content) : file.content;
    const lang    = file.language;
    parts.push(`\`\`\`${lang}`, content, '```', '');
  }

  return parts.join('\n');
}

// ── XML ───────────────────────────────────────────────────────────────────────

function formatXml(opts: FormatOptions): string {
  const esc = (s: string) => s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');

  const parts: string[] = [];
  parts.push('<?xml version="1.0" encoding="UTF-8"?>');
  parts.push('<filer_pack>');

  parts.push('<file_summary>');
  parts.push(`  <repo>${esc(opts.repoName)}</repo>`);
  parts.push(`  <generated_at>${opts.generatedAt}</generated_at>`);
  parts.push(`  <total_files>${opts.totalFiles}</total_files>`);
  parts.push(`  <total_tokens>${opts.totalTokens}</total_tokens>`);
  if (opts.headerText) parts.push(`  <header>${esc(opts.headerText)}</header>`);
  parts.push('</file_summary>');

  if (opts.instructions) {
    parts.push('<instructions>');
    parts.push(esc(opts.instructions));
    parts.push('</instructions>');
  }

  if (opts.preamble) {
    parts.push('<knowledge_summary>');
    parts.push(esc(opts.preamble));
    parts.push('</knowledge_summary>');
  }

  if (opts.tree) {
    parts.push('<directory_structure>');
    parts.push(esc(opts.tree));
    parts.push('</directory_structure>');
  }

  parts.push('<files>');
  for (const file of opts.files) {
    const content = opts.showLineNumbers ? addLineNumbers(file.content) : file.content;
    parts.push(`  <file path="${esc(file.path)}" language="${esc(file.language)}" tokens="${file.tokens}">`);
    parts.push(esc(content));
    parts.push('  </file>');
  }
  parts.push('</files>');

  parts.push('</filer_pack>');
  return parts.join('\n');
}

// ── JSON ──────────────────────────────────────────────────────────────────────

function formatJson(opts: FormatOptions): string {
  const output = {
    fileSummary: {
      repo:         opts.repoName,
      generatedAt:  opts.generatedAt,
      totalFiles:   opts.totalFiles,
      totalTokens:  opts.totalTokens,
      headerText:   opts.headerText ?? null,
    },
    instructions:       opts.instructions ?? null,
    knowledgeSummary:   opts.preamble ?? null,
    directoryStructure: opts.tree ?? null,
    files: opts.files.reduce((acc, f) => {
      const content = opts.showLineNumbers ? addLineNumbers(f.content) : f.content;
      acc[f.path] = { content, language: f.language, tokens: f.tokens, size: f.size };
      return acc;
    }, {} as Record<string, { content: string; language: string; tokens: number; size: number }>),
  };
  return JSON.stringify(output, null, 2);
}

// ── Plain text ────────────────────────────────────────────────────────────────

function formatPlain(opts: FormatOptions): string {
  const sep  = '='.repeat(64);
  const sep2 = '-'.repeat(64);
  const parts: string[] = [];

  parts.push(sep);
  parts.push(`Filer Pack — ${opts.repoName}`);
  parts.push(`Generated: ${opts.generatedAt} · ${opts.totalFiles} files · ~${opts.totalTokens.toLocaleString()} tokens`);
  parts.push(sep, '');

  if (opts.instructions) {
    parts.push(sep, 'INSTRUCTIONS', sep, '', opts.instructions, '');
  }

  if (opts.preamble) {
    parts.push(sep, 'KNOWLEDGE SUMMARY', sep, '', opts.preamble, '');
  }

  if (opts.tree) {
    parts.push(sep, 'DIRECTORY STRUCTURE', sep, '', opts.tree, '');
  }

  parts.push(sep, 'FILES', sep, '');

  for (const file of opts.files) {
    const content = opts.showLineNumbers ? addLineNumbers(file.content) : file.content;
    parts.push(sep2);
    parts.push(`File: ${file.path}  [${file.language}, ~${file.tokens} tokens]`);
    parts.push(sep2);
    parts.push(content, '');
  }

  return parts.join('\n');
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function addLineNumbers(content: string): string {
  const lines  = content.split('\n');
  const width  = String(lines.length).length;
  return lines
    .map((line, i) => `${String(i + 1).padStart(width, ' ')} | ${line}`)
    .join('\n');
}
