import fs   from 'fs';
import path from 'path';
import chalk from 'chalk';
import { readAllNodes, readIndex, filerExists } from '../store/mod.js';
import { AnyNode, NodeType, NODE_PRIORITY } from '../schema/mod.js';

interface ExportOptions {
  type?:       string;
  scope?:      string;
  verified?:   boolean;
  output?:     string;
  noHeader?:   boolean;
}

export async function exportCommand(options: ExportOptions): Promise<void> {
  const root = process.cwd();

  if (!filerExists(root)) {
    console.error(chalk.red('\n  No .filer/ directory found. Run: filer init\n'));
    process.exit(1);
  }

  let nodes = readAllNodes(root);

  if (options.type) {
    const types = options.type.split(',').map(t => t.trim()) as NodeType[];
    nodes = nodes.filter(n => types.includes(n.type));
  }

  if (options.scope) {
    const scope = options.scope;
    nodes = nodes.filter(n =>
      n.scope.some(s => s.includes(scope) || scope.includes(s.replace('/**', '').replace('/*', '')))
    );
  }

  if (options.verified !== undefined) {
    nodes = nodes.filter(n => n.verified === options.verified);
  }

  if (nodes.length === 0) {
    process.stderr.write(chalk.yellow('  No nodes match the given filters.\n'));
    return;
  }

  nodes.sort((a, b) => (NODE_PRIORITY[a.type] ?? 9) - (NODE_PRIORITY[b.type] ?? 9));

  const index  = readIndex(root);
  const repo   = index?.repo ?? path.basename(root);
  const markdown = buildMarkdown(nodes, repo, options.noHeader);

  if (options.output) {
    const absPath = path.resolve(root, options.output);
    fs.mkdirSync(path.dirname(absPath), { recursive: true });
    fs.writeFileSync(absPath, markdown, 'utf-8');
    process.stderr.write(chalk.green(`  Exported ${nodes.length} node(s) to ${options.output}\n`));
  } else {
    // Write to stdout — pipe-friendly
    process.stdout.write(markdown);
  }
}

// ── Markdown builder ──────────────────────────────────────────────────────────

function buildMarkdown(nodes: AnyNode[], repo: string, noHeader?: boolean): string {
  const lines: string[] = [];

  if (!noHeader) {
    lines.push(`# Filer Knowledge Layer — ${repo}`);
    lines.push('');
    lines.push(`> Generated by [Filer](https://github.com/dkeswani/filer) · ${new Date().toISOString().slice(0, 10)} · ${nodes.length} node(s)`);
    lines.push('');
    lines.push('This file contains structured knowledge extracted from the codebase. Load it before writing code to understand constraints, dangers, patterns, and decisions that are not visible from reading the code alone.');
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Group by type in priority order
  const byType = new Map<NodeType, AnyNode[]>();
  for (const node of nodes) {
    const list = byType.get(node.type) ?? [];
    list.push(node);
    byType.set(node.type, list);
  }

  const TYPE_HEADINGS: Record<string, string> = {
    security:    '## Security Rules',
    constraint:  '## Constraints',
    danger:      '## Dangers',
    assumption:  '## Assumptions',
    antipattern: '## Antipatterns',
    pattern:     '## Patterns',
    intent:      '## Module Intent',
    decision:    '## Decisions',
  };

  for (const [type, typeNodes] of byType) {
    lines.push(TYPE_HEADINGS[type] ?? `## ${type}`);
    lines.push('');

    for (const node of typeNodes) {
      lines.push(...nodeToMarkdown(node));
      lines.push('');
    }
  }

  return lines.join('\n');
}

function nodeToMarkdown(node: AnyNode): string[] {
  const lines: string[] = [];
  const verifiedTag = node.verified ? ' ✓' : '';
  const staleTag    = node.stale_risk >= 0.5 ? ' ⚠' : '';
  const conf        = Math.round(node.confidence * 100);

  lines.push(`### \`${node.id}\`${verifiedTag}${staleTag}`);
  lines.push('');
  lines.push(`**Scope:** ${node.scope.join(', ')}  `);
  lines.push(`**Confidence:** ${conf}%`);

  if (node.tags.length > 0) {
    lines.push(`**Tags:** ${node.tags.join(', ')}`);
  }
  lines.push('');

  switch (node.type) {
    case 'security':
      lines.push(`**Severity:** ${node.severity.toUpperCase()}  `);
      lines.push(`**Category:** ${node.category}  `);
      lines.push('');
      lines.push(`**Rule:** ${node.statement}`);
      lines.push('');
      lines.push(`**Because:** ${node.because}`);
      lines.push('');
      lines.push(`**If violated:** ${node.if_violated}`);
      lines.push('');
      lines.push(`**Safe pattern:** ${node.safe_pattern}`);
      if (node.audit_required) {
        lines.push('');
        lines.push(`> ⚑ Audit required${node.audit_format ? `: ${node.audit_format}` : ''}`);
      }
      break;

    case 'constraint':
      lines.push(`**Statement:** ${node.statement}`);
      lines.push('');
      lines.push(`**Because:** ${node.because}`);
      lines.push('');
      lines.push(`**If violated:** ${node.if_violated}`);
      if (node.instead) {
        lines.push('');
        lines.push(`**Instead:** ${node.instead}`);
      }
      break;

    case 'danger':
      lines.push(`**Statement:** ${node.statement}`);
      lines.push('');
      lines.push(`**Condition:** ${node.condition}`);
      lines.push('');
      lines.push(`**Safe pattern:** ${node.safe_pattern}`);
      if (node.current_mitigation) {
        lines.push('');
        lines.push(`**Current mitigation:** ${node.current_mitigation}`);
      }
      if (node.history) {
        lines.push('');
        lines.push(`**History:** ${node.history}`);
      }
      break;

    case 'assumption':
      lines.push(`**Statement:** ${node.statement}`);
      lines.push('');
      lines.push(`**Breaks when:** ${node.breaks_when}`);
      if (node.boundary) {
        lines.push('');
        lines.push(`**Boundary:** ${node.boundary}`);
      }
      if (node.relied_on_by.length > 0) {
        lines.push('');
        lines.push(`**Relied on by:** ${node.relied_on_by.join(', ')}`);
      }
      break;

    case 'antipattern':
      lines.push(`**Statement:** ${node.statement}`);
      lines.push('');
      lines.push(`**Looks right because:** ${node.why_it_looks_right}`);
      lines.push('');
      lines.push(`**Wrong here because:** ${node.why_its_wrong_here}`);
      lines.push('');
      lines.push(`**Correct pattern:** ${node.correct_pattern}`);
      if (node.history) {
        lines.push('');
        lines.push(`**History:** ${node.history}`);
      }
      break;

    case 'pattern':
      lines.push(`**Statement:** ${node.statement}`);
      lines.push('');
      lines.push(`**Why:** ${node.why}`);
      if (node.structure) {
        lines.push('');
        lines.push(`**Structure:** ${node.structure}`);
      }
      if (node.anti_pattern) {
        lines.push('');
        lines.push(`**Anti-pattern:** ${node.anti_pattern}`);
      }
      if (node.deviations.length > 0) {
        lines.push('');
        lines.push('**Deviations:**');
        for (const d of node.deviations) {
          lines.push(`- \`${d.scope}\`: ${d.reason}`);
        }
      }
      break;

    case 'intent':
      lines.push(`**Purpose:** ${node.purpose}`);
      if (node.owns.length > 0) {
        lines.push('');
        lines.push('**Owns:**');
        for (const o of node.owns) lines.push(`- ${o}`);
      }
      if (node.does_not_own.length > 0) {
        lines.push('');
        lines.push('**Does NOT own:**');
        for (const o of node.does_not_own) lines.push(`- ${o}`);
      }
      if (node.entry_points.length > 0) {
        lines.push('');
        lines.push(`**Entry points:** ${node.entry_points.join(', ')}`);
      }
      break;

    case 'decision':
      lines.push(`**Statement:** ${node.statement}`);
      lines.push('');
      lines.push(`**Reason:** ${node.reason}`);
      if (node.revisit_if) {
        lines.push('');
        lines.push(`**Revisit if:** ${node.revisit_if}`);
      }
      if (node.alternatives_rejected.length > 0) {
        lines.push('');
        lines.push('**Alternatives rejected:**');
        for (const alt of node.alternatives_rejected) {
          lines.push(`- **${alt.option}:** ${alt.why_rejected}`);
        }
      }
      break;
  }

  if (node.must_not.length > 0) {
    lines.push('');
    lines.push('**Must NOT:**');
    for (const m of node.must_not) lines.push(`- ${m}`);
  }

  if (node.related.length > 0) {
    lines.push('');
    lines.push(`**Related:** ${node.related.join(', ')}`);
  }

  lines.push('');
  lines.push('---');

  return lines;
}
